# Generated by Django 5.0.6 on 2024-06-27 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='speciality',
            table='Speciality',
        ),
    ]
