# Generated by Django 5.0.6 on 2024-06-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_speciality_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciality',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
