# Generated by Django 5.0.6 on 2024-06-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('speciality', models.ManyToManyField(to='courses.speciality')),
                ('teacher', models.ManyToManyField(to='courses.teacher')),
            ],
            options={
                'db_table': 'Subject',
            },
        ),
    ]
