# Generated by Django 5.0.6 on 2024-06-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_subject_code_subject_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciality',
            name='duration',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
