# Generated by Django 5.0.6 on 2024-07-06 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_speciality_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciality',
            name='duration',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 7, 6, 10, 49, 28, 441353)),
        ),
    ]
