# Generated by Django 5.0.6 on 2024-07-06 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_speciality_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciality',
            name='start_date',
            field=models.DateField(default=datetime.timezone),
        ),
    ]
