# Generated by Django 5.0.6 on 2024-07-06 10:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_speciality_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciality',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 7, 6, 10, 51, 17, 561366, tzinfo=datetime.timezone.utc)),
        ),
    ]
