# Generated by Django 5.0.6 on 2024-07-06 10:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_speciality_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciality',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
