# Generated by Django 5.0.6 on 2024-07-18 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_speciality_start_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speciality',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='speciality',
            name='duration_unit',
            field=models.CharField(choices=[('weeks', 'Weeks'), ('months', 'Months'), ('years', 'Years')], default='years', max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
